# mock_locations.py — Curated list of interesting locations for testing.
# Used by telemetry.py when USE_MOCK_TELEMETRY = True in config.py.
# Each entry is a realistic snapshot: position, altitude, heading, speed.

MOCK_LOCATIONS = [
    {
        "name":        "Grand Canyon South Rim",
        "lat":         36.0544,
        "lon":        -112.1401,
        "altitude":    7000,    # feet MSL
        "altitude_agl": 2000,   # feet above ground
        "heading":     270.0,   # degrees true
        "airspeed":    120.0,   # knots
        "groundspeed": 125.0,
        "vertical_speed": 0.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
    {
        "name":        "Mount Rainier",
        "lat":         46.8523,
        "lon":        -121.7603,
        "altitude":    14500,
        "altitude_agl": 500,
        "heading":     180.0,
        "airspeed":    150.0,
        "groundspeed": 155.0,
        "vertical_speed": -200.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
    {
        "name":        "Yellowstone Caldera",
        "lat":         44.4280,
        "lon":        -110.5885,
        "altitude":    8500,
        "altitude_agl": 2500,
        "heading":     45.0,
        "airspeed":    130.0,
        "groundspeed": 140.0,
        "vertical_speed": 0.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
    {
        "name":        "Manhattan, New York",
        "lat":         40.7580,
        "lon":        -73.9855,
        "altitude":    2500,
        "altitude_agl": 2500,
        "heading":     90.0,
        "airspeed":    110.0,
        "groundspeed": 115.0,
        "vertical_speed": 0.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
    {
        "name":        "Golden Gate Bridge",
        "lat":         37.8199,
        "lon":        -122.4783,
        "altitude":    1500,
        "altitude_agl": 1500,
        "heading":     135.0,
        "airspeed":    100.0,
        "groundspeed": 105.0,
        "vertical_speed": 0.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
    {
        "name":        "Glacier National Park",
        "lat":         48.7596,
        "lon":        -113.7870,
        "altitude":    9000,
        "altitude_agl": 3000,
        "heading":     0.0,
        "airspeed":    140.0,
        "groundspeed": 150.0,
        "vertical_speed": 0.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
    {
        "name":        "Niagara Falls",
        "lat":         43.0962,
        "lon":        -79.0377,
        "altitude":    1000,
        "altitude_agl": 700,
        "heading":     270.0,
        "airspeed":    90.0,
        "groundspeed": 95.0,
        "vertical_speed": 0.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
    {
        "name":        "Great Salt Lake, Utah",
        "lat":         41.1279,
        "lon":        -112.2430,
        "altitude":    5500,
        "altitude_agl": 1000,
        "heading":     180.0,
        "airspeed":    120.0,
        "groundspeed": 125.0,
        "vertical_speed": 0.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
    {
        "name":        "Denali, Alaska",
        "lat":         63.0695,
        "lon":        -151.0074,
        "altitude":    20400,
        "altitude_agl": 800,
        "heading":     90.0,
        "airspeed":    160.0,
        "groundspeed": 170.0,
        "vertical_speed": 0.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
    {
        "name":        "Florida Keys",
        "lat":         24.7102,
        "lon":        -81.0998,
        "altitude":    800,
        "altitude_agl": 800,
        "heading":     225.0,
        "airspeed":    95.0,
        "groundspeed": 100.0,
        "vertical_speed": 0.0,
        "aircraft":   "Cessna 172",
        "on_ground":   False,
    },
]

# Quick lookup by name
MOCK_LOCATIONS_BY_NAME = {loc["name"]: loc for loc in MOCK_LOCATIONS}
